
interface _GlobalComponents {
      'AddToCartBtnVue': typeof import("../components/AddToCartBtnVue.vue")['default']
    'AlertVue': typeof import("../components/AlertVue.vue")['default']
    'CarouselVue': typeof import("../components/CarouselVue.vue")['default']
    'CheckoutVue': typeof import("../components/CheckoutVue.vue")['default']
    'FiltersVue': typeof import("../components/FiltersVue.vue")['default']
    'FooterVue': typeof import("../components/FooterVue.vue")['default']
    'HeaderVue': typeof import("../components/HeaderVue.vue")['default']
    'ModalWindowVue': typeof import("../components/ModalWindowVue.vue")['default']
    'ProductImageBigVue': typeof import("../components/ProductImageBigVue.vue")['default']
    'ProductImageVue': typeof import("../components/ProductImageVue.vue")['default']
    'ScrollVue': typeof import("../components/ScrollVue.vue")['default']
    'CartItemVue': typeof import("../components/cart/CartItemVue.vue")['default']
    'CartListVue': typeof import("../components/cart/CartListVue.vue")['default']
    'HomeAboutVue': typeof import("../components/home/AboutVue.vue")['default']
    'HomeBrandsListVue': typeof import("../components/home/BrandsListVue.vue")['default']
    'HomeBrandsVue': typeof import("../components/home/BrandsVue.vue")['default']
    'HomeHeroVue': typeof import("../components/home/HeroVue.vue")['default']
    'NavbarButtonVue': typeof import("../components/navbar/NavbarButtonVue.vue")['default']
    'NavbarListVue': typeof import("../components/navbar/NavbarListVue.vue")['default']
    'NavbarVue': typeof import("../components/navbar/NavbarVue.vue")['default']
    'ProductsItemVue': typeof import("../components/products/ProductsItemVue.vue")['default']
    'ProductsList': typeof import("../components/products/ProductsList.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAddToCartBtnVue': typeof import("../components/AddToCartBtnVue.vue")['default']
    'LazyAlertVue': typeof import("../components/AlertVue.vue")['default']
    'LazyCarouselVue': typeof import("../components/CarouselVue.vue")['default']
    'LazyCheckoutVue': typeof import("../components/CheckoutVue.vue")['default']
    'LazyFiltersVue': typeof import("../components/FiltersVue.vue")['default']
    'LazyFooterVue': typeof import("../components/FooterVue.vue")['default']
    'LazyHeaderVue': typeof import("../components/HeaderVue.vue")['default']
    'LazyModalWindowVue': typeof import("../components/ModalWindowVue.vue")['default']
    'LazyProductImageBigVue': typeof import("../components/ProductImageBigVue.vue")['default']
    'LazyProductImageVue': typeof import("../components/ProductImageVue.vue")['default']
    'LazyScrollVue': typeof import("../components/ScrollVue.vue")['default']
    'LazyCartItemVue': typeof import("../components/cart/CartItemVue.vue")['default']
    'LazyCartListVue': typeof import("../components/cart/CartListVue.vue")['default']
    'LazyHomeAboutVue': typeof import("../components/home/AboutVue.vue")['default']
    'LazyHomeBrandsListVue': typeof import("../components/home/BrandsListVue.vue")['default']
    'LazyHomeBrandsVue': typeof import("../components/home/BrandsVue.vue")['default']
    'LazyHomeHeroVue': typeof import("../components/home/HeroVue.vue")['default']
    'LazyNavbarButtonVue': typeof import("../components/navbar/NavbarButtonVue.vue")['default']
    'LazyNavbarListVue': typeof import("../components/navbar/NavbarListVue.vue")['default']
    'LazyNavbarVue': typeof import("../components/navbar/NavbarVue.vue")['default']
    'LazyProductsItemVue': typeof import("../components/products/ProductsItemVue.vue")['default']
    'LazyProductsList': typeof import("../components/products/ProductsList.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AddToCartBtnVue: typeof import("../components/AddToCartBtnVue.vue")['default']
export const AlertVue: typeof import("../components/AlertVue.vue")['default']
export const CarouselVue: typeof import("../components/CarouselVue.vue")['default']
export const CheckoutVue: typeof import("../components/CheckoutVue.vue")['default']
export const FiltersVue: typeof import("../components/FiltersVue.vue")['default']
export const FooterVue: typeof import("../components/FooterVue.vue")['default']
export const HeaderVue: typeof import("../components/HeaderVue.vue")['default']
export const ModalWindowVue: typeof import("../components/ModalWindowVue.vue")['default']
export const ProductImageBigVue: typeof import("../components/ProductImageBigVue.vue")['default']
export const ProductImageVue: typeof import("../components/ProductImageVue.vue")['default']
export const ScrollVue: typeof import("../components/ScrollVue.vue")['default']
export const CartItemVue: typeof import("../components/cart/CartItemVue.vue")['default']
export const CartListVue: typeof import("../components/cart/CartListVue.vue")['default']
export const HomeAboutVue: typeof import("../components/home/AboutVue.vue")['default']
export const HomeBrandsListVue: typeof import("../components/home/BrandsListVue.vue")['default']
export const HomeBrandsVue: typeof import("../components/home/BrandsVue.vue")['default']
export const HomeHeroVue: typeof import("../components/home/HeroVue.vue")['default']
export const NavbarButtonVue: typeof import("../components/navbar/NavbarButtonVue.vue")['default']
export const NavbarListVue: typeof import("../components/navbar/NavbarListVue.vue")['default']
export const NavbarVue: typeof import("../components/navbar/NavbarVue.vue")['default']
export const ProductsItemVue: typeof import("../components/products/ProductsItemVue.vue")['default']
export const ProductsList: typeof import("../components/products/ProductsList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAddToCartBtnVue: typeof import("../components/AddToCartBtnVue.vue")['default']
export const LazyAlertVue: typeof import("../components/AlertVue.vue")['default']
export const LazyCarouselVue: typeof import("../components/CarouselVue.vue")['default']
export const LazyCheckoutVue: typeof import("../components/CheckoutVue.vue")['default']
export const LazyFiltersVue: typeof import("../components/FiltersVue.vue")['default']
export const LazyFooterVue: typeof import("../components/FooterVue.vue")['default']
export const LazyHeaderVue: typeof import("../components/HeaderVue.vue")['default']
export const LazyModalWindowVue: typeof import("../components/ModalWindowVue.vue")['default']
export const LazyProductImageBigVue: typeof import("../components/ProductImageBigVue.vue")['default']
export const LazyProductImageVue: typeof import("../components/ProductImageVue.vue")['default']
export const LazyScrollVue: typeof import("../components/ScrollVue.vue")['default']
export const LazyCartItemVue: typeof import("../components/cart/CartItemVue.vue")['default']
export const LazyCartListVue: typeof import("../components/cart/CartListVue.vue")['default']
export const LazyHomeAboutVue: typeof import("../components/home/AboutVue.vue")['default']
export const LazyHomeBrandsListVue: typeof import("../components/home/BrandsListVue.vue")['default']
export const LazyHomeBrandsVue: typeof import("../components/home/BrandsVue.vue")['default']
export const LazyHomeHeroVue: typeof import("../components/home/HeroVue.vue")['default']
export const LazyNavbarButtonVue: typeof import("../components/navbar/NavbarButtonVue.vue")['default']
export const LazyNavbarListVue: typeof import("../components/navbar/NavbarListVue.vue")['default']
export const LazyNavbarVue: typeof import("../components/navbar/NavbarVue.vue")['default']
export const LazyProductsItemVue: typeof import("../components/products/ProductsItemVue.vue")['default']
export const LazyProductsList: typeof import("../components/products/ProductsList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
